export default {
  panels: [
    {
      index: 0,
      name: 1,
      height: 70,
      width: 210,
      paperHeader: 0,
      paperFooter: 196.875,
      printElements: [
        {
          options: {
            left: 5,
            top: 6,
            height: 189,
            width: 583.5,
            coordinateSync: false,
            widthHeightSync: false,
            borderColor: "#9100ff",
            right: 588,
            bottom: 188.25,
            vCenter: 296.25,
            hCenter: 93.75,
          },
          printElementType: { title: "矩形", type: "rect" },
        },
        {
          options: {
            left: 90,
            top: 21,
            height: 123,
            width: 130.5,
            field: "qrcode",
            testData: "XS888888888",
            fontSize: 12,
            lineHeight: 18,
            textType: "qrcode",
            title: "二维码",
            right: 278.25,
            bottom: 127.5,
            vCenter: 211.5,
            hCenter: 71.25,
          },
          printElementType: { title: "二维码", type: "text" },
        },
        {
          options: {
            left: 231,
            top: 27,
            height: 17,
            width: 120,
            testData: "平台名称",
            fontSize: 16.5,
            fontWeight: "700",
            textAlign: "center",
            hideTitle: true,
            title: "中间模板",
            right: 262.5,
            bottom: 38,
            vCenter: 202.5,
            hCenter: 29.5,
          },
          printElementType: { title: "平台名称", type: "text" },
        },
        {
          options: {
            left: 231,
            top: 64.5,
            height: 16,
            width: 120,
            field: "orderId",
            testData: "XS888888888",
            fontSize: 6.75,
            fontWeight: "700",
            textAlign: "left",
            textContentVerticalAlign: "middle",
            title: "订单编号",
            right: 133.5,
            bottom: 86.5,
            vCenter: 73.5,
            hCenter: 78.5,
          },
          printElementType: { title: "订单编号", type: "text" },
        },
        {
          options: {
            left: 231,
            top: 99,
            height: 16,
            width: 120,
            field: "date",
            testData: "2023-05-01",
            fontSize: 6.75,
            fontWeight: "700",
            textAlign: "left",
            textContentVerticalAlign: "middle",
            title: "业务日期",
            right: 134.25,
            bottom: 122.5,
            vCenter: 74.25,
            hCenter: 114.5,
          },
          printElementType: { title: "业务日期", type: "text" },
        },
        {
          options: {
            left: 231,
            top: 130.5,
            height: 16,
            width: 120,
            field: "creator",
            testData: "李四",
            fontSize: 6.75,
            fontWeight: "700",
            textAlign: "left",
            textContentVerticalAlign: "middle",
            title: "制单人",
            right: 137.25,
            bottom: 140.5,
            vCenter: 77.25,
            hCenter: 132.5,
          },
          printElementType: { title: "制单人", type: "text" },
        },
        {
          options: {
            left: 370.5,
            top: 21,
            height: 123,
            width: 130.5,
            field: "qrcode",
            testData: "XS888888888",
            fontSize: 12,
            lineHeight: 18,
            textType: "qrcode",
            title: "二维码",
            right: 421.5,
            bottom: 137.25,
            vCenter: 356.25,
            hCenter: 75.75,
          },
          printElementType: { title: "二维码", type: "text" },
        },
      ],
      paperNumberLeft: 267,
      paperNumberTop: 176,
      paperNumberDisabled: true,
      watermarkOptions: {},
    },
  ],
};
